name: Deploy Staging

on:
  push:
    branches: ['staging']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy enviroment files
        run: cp .env.staging .env

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: zeinersyad/${{env.APP_NAME}}:staging
          outputs: type=docker,dest=/tmp/${{env.APP_NAME}}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}
          path: /tmp/${{env.APP_NAME}}.tar

  deploy:
    runs-on: self-hosted
    environment: staging
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy enviroment files
        run: cp .env.staging .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{env.APP_NAME}}
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/${{env.APP_NAME}}.tar
          docker image ls -a

      - name: Build the Docker image
        run: docker-compose -p kassku-staging_server up -d
