image: docker:20.10.16

variables:
  DEPLOY_NAME: "maresto-stock-opname-server"

stages:
    - prepare
    - build
    - deploy

services:
  - docker:20.10.16-dind

default:
  before_script:
    - docker info
  tags:
    - saas-linux-medium-amd64

prepare-copy-env-to-project:
    stage: prepare
    only:
        refs:
            - staging
            - production
    script:
        - |
            echo "$CI_COMMIT_BRANCH"
            echo "$ENV_STAGING"
            if [ "$CI_COMMIT_BRANCH" == "staging" ]; then echo "$ENV_STAGING" > "$(pwd)/.env"
            elif [ "$CI_COMMIT_BRANCH" == "production" ]; then echo "$ENV_PRODUCTION" > "$(pwd)/.env"
            fi
    artifacts:
        paths:
            - .env
        expire_in: 1 days
        when: always


build-on-shared-runner:
    stage: build
    dependencies:
        - "prepare-copy-env-to-project"
    only:
        refs:
            - staging
            - production
    script:
        - DOCKER_BUILDKIT=1 docker build -t $DEPLOY_NAME:$CI_COMMIT_REF_NAME -o type=tar,dest=$DEPLOY_NAME.tar .
    artifacts:
        paths:
            - $DEPLOY_NAME.tar
        expire_in: 1 days
        when: always

load-and-deploy-artifact-to-server:
    stage: deploy
    dependencies:
        - "prepare-copy-env-to-project"
        - "build-on-shared-runner"
    tags:
        - production
        - staging
        - vps
    only:
        refs:
            - staging
            - production
    script:
        - cat $DEPLOY_NAME.tar | docker import --change 'CMD ["/usr/local/bin/stock-opname-server"]' - $DEPLOY_NAME:$CI_COMMIT_REF_NAME
        - docker image ls -a
        - docker-compose -p $DEPLOY_NAME:$CI_COMMIT_REF_NAME up -d