version: "3"

services:
    webserver:
        image: ${APP_NAME}:${ENV}
        container_name: ${APP_NAME}
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - 9001:9001
        tty: true
        environment:
            SERVICE_NAME: "${APP_NAME}"
            SERVICE_TAGS: "${ENV}"
            DATABASE_URL: "${DATABASE_URL}"
            APP_NAME: "${APP_NAME}"
            APP_HOST: "${APP_HOST}"
            APPKEY: "${APPKEY}"
            SERVER_HOST: "${SERVER_HOST}"
            SERVER_PORT: "${SERVER_PORT}"
            PG_USER: "${PG_USER}"
            PG_PASSWORD: "${PG_PASSWORD}"
            PG_HOST: "${PG_HOST}"
            PG_PORT: "${PG_PORT}"
            PG_DBNAME: "${PG_DBNAME}"
            PG_POOLMINSIZE: "${PG_POOLMINSIZE}"
            PG_POOLMAXSIZE: "${PG_POOLMAXSIZE}"
